modLoader="javafml"
loaderVersion="[36,)"
license="license.txt"
issueTrackerURL="https://github.com/InfinityRaider/3DManeuverGear/issues/"

[[mods]]
modId="maneuver_gear"
version="1.16.5-2.0.5"
displayName="3D Maneuver Gear"
displayURL="https://www.curseforge.com/minecraft/mc-mods/d-maneuver-gear"
logoFile="logo.png"
authors="InfinityRaider"
description='''
Adds the 3D Maneuver Gear from Attack on Titan to Minecraft
'''

[[dependencies.maneuver_gear]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.maneuver_gear]]
    modId="infinitylib"
    mandatory=true
    versionRange="[1.18.2-2.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.maneuver_gear]]
    modId="curios"
    mandatory=true
    ordering="AFTER"
    versionRange="[1.18.2-5.0.6.0,)"
    side="BOTH"